// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCseMBFJMuMR1MqGIYbz1pEtWpl9Eqik',
    appId: '1:760222781310:web:7b121a19d7db54a55d2d2f',
    messagingSenderId: '760222781310',
    projectId: 'authtutorial-505a9',
    authDomain: 'authtutorial-505a9.firebaseapp.com',
    storageBucket: 'authtutorial-505a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWoN5lCO42QxW75Nf0ONmXPfQ39PPZG0',
    appId: '1:760222781310:android:93faa84b54c8ab2d5d2d2f',
    messagingSenderId: '760222781310',
    projectId: 'authtutorial-505a9',
    storageBucket: 'authtutorial-505a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQf8uphjxMuSzxfNDSnOh2Ol4wc1FU0bQ',
    appId: '1:760222781310:ios:88c6925c1efaf0bb5d2d2f',
    messagingSenderId: '760222781310',
    projectId: 'authtutorial-505a9',
    storageBucket: 'authtutorial-505a9.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQf8uphjxMuSzxfNDSnOh2Ol4wc1FU0bQ',
    appId: '1:760222781310:ios:88c6925c1efaf0bb5d2d2f',
    messagingSenderId: '760222781310',
    projectId: 'authtutorial-505a9',
    storageBucket: 'authtutorial-505a9.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCseMBFJMuMR1MqGIYbz1pEtWpl9Eqik',
    appId: '1:760222781310:web:e59576d6c89417c25d2d2f',
    messagingSenderId: '760222781310',
    projectId: 'authtutorial-505a9',
    authDomain: 'authtutorial-505a9.firebaseapp.com',
    storageBucket: 'authtutorial-505a9.appspot.com',
  );
}
